src/Sidio.Sitemap.AspNetCore.Examples.MvcWebApplication/Models/ErrorViewModel.cs
using System.Diagnostics.CodeAnalysis;

namespace Sidio.Sitemap.AspNetCore.Examples.MvcWebApplication.Models;

[ExcludeFromCodeCoverage]
public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

src/Sidio.Sitemap.AspNetCore.Examples.MvcWebApplication/Controllers/HomeController.cs
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using Microsoft.AspNetCore.Mvc;
using Sidio.Sitemap.AspNetCore.Examples.MvcWebApplication.Models;

namespace Sidio.Sitemap.AspNetCore.Examples.MvcWebApplication.Controllers;

[ExcludeFromCodeCoverage]
public class HomeController : Controller
{
    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

src/Sidio.Sitemap.AspNetCore.Examples.MvcWebApplication/Controllers/NewsController.cs
using System.Diagnostics.CodeAnalysis;
using Microsoft.AspNetCore.Mvc;

namespace Sidio.Sitemap.AspNetCore.Examples.MvcWebApplication.Controllers;

[ExcludeFromCodeCoverage]
public sealed class NewsController : Controller
{
    public string Article1()
    {
        return "article1";
    }
}

src/Sidio.Sitemap.AspNetCore.Examples.MvcWebApplication/Controllers/SitemapController.cs
using System.Diagnostics.CodeAnalysis;
using Microsoft.AspNetCore.Mvc;
using Sidio.Sitemap.Core;
using Sidio.Sitemap.Core.Extensions;

namespace Sidio.Sitemap.AspNetCore.Examples.MvcWebApplication.Controllers;

[ExcludeFromCodeCoverage]
public sealed class SitemapController : Controller
{
    [Route("sitemap.xml")]
    public IActionResult SitemapIndex()
    {
        var sitemapIndex = new SitemapIndex();
        _ = sitemapIndex.TryAdd(Url.Action("SitemapHome"));
        _ = sitemapIndex.TryAdd(Url.Action("SitemapNews"));
        _ = sitemapIndex.TryAdd(Url.Action("SitemapImages"));
        _ = sitemapIndex.TryAdd(Url.Action("SitemapVideos"));

        return new SitemapResult(sitemapIndex);
    }

    [Route("sitemap-home.xml")]
    public IActionResult SitemapHome()
    {
        var sitemap = new Core.Sitemap();

        // handle null warnings by using the TryAdd function
        _ = sitemap.TryAdd(Url.Action("Index", "Home"));
        _ = sitemap.TryAdd(Url.Action("Privacy", "Home"));

        return new SitemapResult(sitemap);
    }

    [Route("sitemap-news.xml")]
    public IActionResult SitemapNews()
    {
        var sitemap = new Core.Sitemap();

        // handle null warnings by checking the URL for null
        var url = Url.Action("Article1", "News");
        if (url != null)
        {
            sitemap.Add(new SitemapNewsNode(url, "Article1", "John Doe", "EN", DateTime.UtcNow));
        }

        return new SitemapResult(sitemap);
    }

    [Route("sitemap-images.xml")]
    public IActionResult SitemapImages()
    {
        var imageLocation = new ImageLocation("non-existing-image.jpg");

        var sitemap = new Core.Sitemap();

        // handle null warnings by using the Create function
        sitemap.Add(SitemapImageNode.Create(Url.Action("Index", "Home"), imageLocation));

        return new SitemapResult(sitemap);
    }

    [Route("sitemap-videos.xml")]
    public IActionResult SitemapVideos()
    {
        var video = new VideoContent("non-existing-video-thumbnail.jpg", "Video1", "Video1 description", "non-existing-video.mp4", null);

        var sitemap = new Core.Sitemap();
        sitemap.Add(SitemapVideoNode.Create(Url.Action("Index", "Home"), video));

        return new SitemapResult(sitemap);
    }
}

src/Sidio.Sitemap.AspNetCore.Examples.MvcWebApplication/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <ul>
        <li><a asp-controller="Sitemap" asp-action="SitemapIndex" target="_blank">View sitemap index</a></li>
        <li><a asp-controller="Sitemap" asp-action="SitemapHome" target="_blank">View sitemap home</a></li>
        <li><a asp-controller="Sitemap" asp-action="SitemapNews" target="_blank">View news sitemap</a></li>
        <li><a asp-controller="Sitemap" asp-action="SitemapImages" target="_blank">View images sitemap</a></li>
        <li><a asp-controller="Sitemap" asp-action="SitemapVideos" target="_blank">View video sitemap</a></li>
    </ul>
</div>

src/Sidio.Sitemap.AspNetCore.Examples.MvcWebApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - Sidio.Sitemap.AspNetCore.Examples.MvcWebApplication</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/Sidio.Sitemap.AspNetCore.Examples.MvcWebApplication.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Sidio.Sitemap.AspNetCore.Examples.MvcWebApplication</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2024 - Sidio.Sitemap.AspNetCore.Examples.MvcWebApplication - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>